#!/usr/bin/env node
/* ============================================================
   build-8posts.js  —  generate the 8posts portfolio grid from
   jasonbrewer.net's data.js.

   WHAT IT DOES
     Reads HOME + PROJECTS out of data.js, keeps every front-page
     project tile (skipping collection tiles and anything flagged
     hide8:true), reshapes each one into the { title, client, img,
     type, id, cat } shape the 8posts grid expects, rewrites the
     relative asset paths to absolute jasonbrewer.net URLs, and
     writes the result into portfolio.html between two markers.

   HOW TO RUN
     node build-8posts.js

   ONE-TIME SETUP (in portfolio.html)
     Replace the hand-written `const ITEMS = [ ... ];` block with
     these two marker lines (the script fills the space between):

       // ITEMS:START  — auto-generated by build-8posts.js, do not edit by hand
       // ITEMS:END

   To hide a project from 8posts: add  hide8:true  to it in data.js.
   To bring it back: delete that line. New projects show up automatically.
============================================================ */

const fs   = require("fs");
const path = require("path");
const vm   = require("vm");

/* ---- CONFIG: edit these three paths for your setup ---- */
const DATA_JS_PATH   = path.resolve(__dirname, "js/data.js");
const PORTFOLIO_PATH = path.resolve(__dirname, "portfolio.html"); // or "../8posts/portfolio.html"
const ORIGIN         = "https://jasonbrewer.net/";

/* ---- category → 8posts filter bucket (broadcast|commercial|documentary) ----
   These are your best-guess mappings. Tweak any line you disagree with,
   or add  cat:"broadcast"  directly on a project in data.js to override. */
const CAT_MAP = {
  "Documentary":              "documentary",
  "Digital Series":           "documentary",
  "International Production":  "documentary",
  "Education":                "documentary",
  "Weather vs. Climate":      "documentary",
  "HGTV":                     "broadcast",
  "Broadcast Television":     "broadcast",
  "Broadcast / PBS":          "broadcast",
  "A&E":                      "broadcast",
  "Discovery Channel":        "broadcast",
  "Culinary":                 "broadcast",
  "Series":                   "broadcast",
  "PBS":                      "broadcast",
  "Corporate":                "commercial",
  "Corporate Ads":            "commercial",
  "Advertising":              "commercial",
  "Institutional":            "commercial",
  "Cinematography":           "commercial",
  "Aerial":                   "commercial"
};
const CAT_DEFAULT = "broadcast";

/* ---- load HOME + PROJECTS out of data.js ---- */
function loadData() {
  const src = fs.readFileSync(DATA_JS_PATH, "utf8");
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(src, sandbox, { filename: "data.js" });
  return { HOME: sandbox.window.HOME || [], PROJECTS: sandbox.window.PROJECTS || [] };
}

/* ---- helpers ---- */
const abs = p => (p && !/^https?:/i.test(p) ? ORIGIN + p.replace(/^\/+/, "") : p);

function slugFromHref(href) {
  const m = /project\.html\?p=([^&]+)/.exec(href || "");
  return m ? m[1] : null;               // null = not a project tile (e.g. a collection)
}

/* pick the first playable YouTube/Vimeo video from a project */
function pickVideo(proj) {
  const candidates = []
    .concat(proj.video ? [proj.video] : [])
    .concat(Array.isArray(proj.videos) ? proj.videos : []);
  for (const v of candidates) {
    if (v && (v.type === "youtube" || v.type === "vimeo") && v.id) {
      return { type: v.type, id: String(v.id) };
    }
  }
  return null;                          // file/embed/none -> renders as a no-video tile
}

function bucketFor(proj) {
  if (proj.cat) return proj.cat;        // explicit override wins
  return CAT_MAP[proj.category] || CAT_DEFAULT;
}

/* ---- build the ITEMS list from HOME order ---- */
function buildItems({ HOME, PROJECTS }) {
  const bySlug = Object.fromEntries(PROJECTS.map(p => [p.slug, p]));
  const items = [];

  for (const tile of HOME) {
    const slug = slugFromHref(tile.href);
    if (!slug) continue;                // skip collection tiles
    const proj = bySlug[slug] || {};
    if (proj.hide8) continue;           // opt-out flag

    const vid = pickVideo(proj);
    const item = {
      title:  tile.title,
      client: proj.category || "",
      img:    abs(tile.thumb),
      cat:    bucketFor(proj)
    };
    if (vid) { item.type = vid.type; item.id = vid.id; }
    items.push(item);
  }
  return items;
}

/* ---- serialize as a readable JS array literal ---- */
function serialize(items) {
  const rows = items.map(it => {
    const parts = [
      `title:${JSON.stringify(it.title)}`,
      `client:${JSON.stringify(it.client)}`,
      `img:${JSON.stringify(it.img)}`
    ];
    if (it.type) parts.push(`type:${JSON.stringify(it.type)}`, `id:${JSON.stringify(it.id)}`);
    parts.push(`cat:${JSON.stringify(it.cat)}`);
    return "  { " + parts.join(", ") + " }";
  });
  return "const ITEMS = [\n" + rows.join(",\n") + "\n];";
}

/* ---- write between the markers in portfolio.html ---- */
function writePortfolio(block) {
  const html  = fs.readFileSync(PORTFOLIO_PATH, "utf8");
  const start = "// ITEMS:START";
  const end   = "// ITEMS:END";
  const re    = new RegExp(start + "[\\s\\S]*?" + end);
  if (!re.test(html)) {
    console.error(
      "\n  Couldn't find the ITEMS markers in portfolio.html.\n" +
      "  Add these two lines where the ITEMS array used to be:\n\n" +
      "    // ITEMS:START  — auto-generated by build-8posts.js, do not edit by hand\n" +
      "    // ITEMS:END\n"
    );
    process.exit(1);
  }
  const replacement =
    start + "  — auto-generated by build-8posts.js, do not edit by hand\n" +
    block + "\n" + end;
  fs.writeFileSync(PORTFOLIO_PATH, html.replace(re, replacement));
}

/* ---- run ---- */
const data  = loadData();
const items = buildItems(data);
writePortfolio(serialize(items));
console.log(`Wrote ${items.length} items to ${PORTFOLIO_PATH}`);
